summon ccoriginal_cc:gloamwing_stalker ~0 ~1 ~0 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~2 ~1 ~0 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~4 ~1 ~0 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~6 ~1 ~0 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~8 ~1 ~0 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~0 ~1 ~2 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~2 ~1 ~2 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~4 ~1 ~2 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~6 ~1 ~2 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~8 ~1 ~2 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~0 ~1 ~4 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~2 ~1 ~4 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~4 ~1 ~4 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~6 ~1 ~4 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~8 ~1 ~4 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~0 ~1 ~6 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~2 ~1 ~6 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~4 ~1 ~6 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~6 ~1 ~6 ccoriginal_cc:gloamwing_test
summon ccoriginal_cc:gloamwing_stalker ~8 ~1 ~6 ccoriginal_cc:gloamwing_test
