// Generated by engineering/ashen-intake/structure-economy/author_ashen_structure_economy.py
export const ASHEN_STRUCTURE_CHEST_TABLES = Object.freeze({
  "burned_camp": {
    "band": "minor_cache",
    "guaranteedRolls": 1,
    "choiceRolls": [
      1,
      2
    ],
    "guaranteed": [
      {
        "typeId": "aionbound:charbone",
        "weight": 45,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:furnace_chitin",
        "weight": 30,
        "min": 1,
        "max": 1
      },
      {
        "typeId": "aionbound:ember_resin",
        "weight": 15,
        "min": 1,
        "max": 1
      },
      {
        "typeId": "aionbound:sulfur_cluster",
        "weight": 10,
        "min": 1,
        "max": 1
      }
    ],
    "choice": [
      {
        "typeId": "aionbound:charbone",
        "weight": 35,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:furnace_chitin",
        "weight": 30,
        "min": 1,
        "max": 1
      },
      {
        "typeId": "aionbound:ember_resin",
        "weight": 20,
        "min": 1,
        "max": 1
      },
      {
        "typeId": "aionbound:sulfur_cluster",
        "weight": 15,
        "min": 1,
        "max": 1
      }
    ]
  },
  "char_wagon": {
    "band": "minor_cache",
    "guaranteedRolls": 1,
    "choiceRolls": [
      1,
      2
    ],
    "guaranteed": [
      {
        "typeId": "aionbound:sulfur_cluster",
        "weight": 45,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:volcanic_glass_shard",
        "weight": 35,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:charbone",
        "weight": 20,
        "min": 1,
        "max": 1
      }
    ],
    "choice": [
      {
        "typeId": "aionbound:sulfur_cluster",
        "weight": 30,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:volcanic_glass_shard",
        "weight": 30,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:charbone",
        "weight": 25,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:ember_resin",
        "weight": 10,
        "min": 1,
        "max": 1
      },
      {
        "typeId": "aionbound:basalt_core",
        "weight": 5,
        "min": 1,
        "max": 1
      }
    ]
  },
  "broken_bridge": {
    "band": "standard_structure",
    "guaranteedRolls": 1,
    "choiceRolls": [
      2,
      4
    ],
    "guaranteed": [
      {
        "typeId": "aionbound:basalt_brick",
        "weight": 40,
        "min": 2,
        "max": 4
      },
      {
        "typeId": "aionbound:char_planks",
        "weight": 35,
        "min": 2,
        "max": 4
      },
      {
        "typeId": "aionbound:volcanic_glass_shard",
        "weight": 25,
        "min": 1,
        "max": 2
      }
    ],
    "choice": [
      {
        "typeId": "aionbound:basalt_brick",
        "weight": 28,
        "min": 1,
        "max": 3
      },
      {
        "typeId": "aionbound:char_planks",
        "weight": 25,
        "min": 1,
        "max": 3
      },
      {
        "typeId": "aionbound:volcanic_glass_shard",
        "weight": 22,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:furnace_chitin",
        "weight": 18,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:basalt_core",
        "weight": 7,
        "min": 1,
        "max": 1
      }
    ]
  },
  "basalt_arch": {
    "band": "landmark_structure",
    "guaranteedRolls": 2,
    "choiceRolls": [
      2,
      4
    ],
    "guaranteed": [
      {
        "typeId": "aionbound:basalt_brick",
        "weight": 45,
        "min": 2,
        "max": 4
      },
      {
        "typeId": "aionbound:cinder_gravel",
        "weight": 35,
        "min": 2,
        "max": 4
      },
      {
        "typeId": "aionbound:heatstone",
        "weight": 20,
        "min": 1,
        "max": 2
      }
    ],
    "choice": [
      {
        "typeId": "aionbound:basalt_brick",
        "weight": 30,
        "min": 1,
        "max": 3
      },
      {
        "typeId": "aionbound:heatstone",
        "weight": 25,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:volcanic_glass_shard",
        "weight": 20,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:basalt_core",
        "weight": 15,
        "min": 1,
        "max": 1
      },
      {
        "typeId": "aionbound:sulfur_cluster",
        "weight": 10,
        "min": 1,
        "max": 1
      }
    ]
  },
  "ash_watchtower": {
    "band": "landmark_structure",
    "guaranteedRolls": 2,
    "choiceRolls": [
      2,
      4
    ],
    "guaranteed": [
      {
        "typeId": "aionbound:sulfur_cluster",
        "weight": 45,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:volcanic_glass_shard",
        "weight": 35,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:charbone",
        "weight": 20,
        "min": 1,
        "max": 2
      }
    ],
    "choice": [
      {
        "typeId": "aionbound:ash_crystal",
        "weight": 22,
        "min": 1,
        "max": 1
      },
      {
        "typeId": "aionbound:volcanic_glass_shard",
        "weight": 25,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:heatstone",
        "weight": 20,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:sulfur_cluster",
        "weight": 18,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:basalt_core",
        "weight": 15,
        "min": 1,
        "max": 1
      }
    ]
  },
  "ancient_kiln": {
    "band": "landmark_structure",
    "guaranteedRolls": 2,
    "choiceRolls": [
      2,
      4
    ],
    "guaranteed": [
      {
        "typeId": "aionbound:heatstone",
        "weight": 45,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:sulfur_cluster",
        "weight": 30,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:basalt_core",
        "weight": 25,
        "min": 1,
        "max": 1
      }
    ],
    "choice": [
      {
        "typeId": "aionbound:heatstone",
        "weight": 28,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:basalt_core",
        "weight": 22,
        "min": 1,
        "max": 1
      },
      {
        "typeId": "aionbound:ember_resin",
        "weight": 20,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:volcanic_glass_shard",
        "weight": 18,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:furnace_chitin",
        "weight": 12,
        "min": 1,
        "max": 1
      }
    ]
  },
  "ash_cave": {
    "band": "standard_structure",
    "guaranteedRolls": 1,
    "choiceRolls": [
      2,
      4
    ],
    "guaranteed": [
      {
        "typeId": "aionbound:heatstone",
        "weight": 45,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:charbone",
        "weight": 35,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:furnace_chitin",
        "weight": 20,
        "min": 1,
        "max": 1
      }
    ],
    "choice": [
      {
        "typeId": "aionbound:heatstone",
        "weight": 30,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:charbone",
        "weight": 25,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:magma_moss",
        "weight": 18,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:furnace_chitin",
        "weight": 17,
        "min": 1,
        "max": 1
      },
      {
        "typeId": "aionbound:basalt_core",
        "weight": 10,
        "min": 1,
        "max": 1
      }
    ]
  },
  "ember_forge": {
    "band": "apex_arena_chest",
    "guaranteedRolls": 2,
    "choiceRolls": [
      2,
      4
    ],
    "guaranteed": [
      {
        "typeId": "aionbound:heatstone",
        "weight": 40,
        "min": 1,
        "max": 3
      },
      {
        "typeId": "aionbound:basalt_core",
        "weight": 35,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:volcanic_glass_shard",
        "weight": 25,
        "min": 1,
        "max": 3
      }
    ],
    "choice": [
      {
        "typeId": "aionbound:heatstone",
        "weight": 25,
        "min": 1,
        "max": 3
      },
      {
        "typeId": "aionbound:basalt_core",
        "weight": 20,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:volcanic_glass_shard",
        "weight": 18,
        "min": 1,
        "max": 3
      },
      {
        "typeId": "aionbound:furnace_chitin",
        "weight": 15,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:ember_resin",
        "weight": 12,
        "min": 1,
        "max": 2
      },
      {
        "typeId": "aionbound:ash_crystal",
        "weight": 10,
        "min": 1,
        "max": 1
      }
    ]
  }
});
export const ASHEN_STRUCTURE_SIGNATURES = Object.freeze([
  {
    "structure": "fire_totem",
    "stamp": "aionbound.structure.ashen.fire_totem.discovered.v1",
    "anchor_id": "fire_totem_prayer",
    "anchor_type": "minecraft:lectern",
    "anchor_coordinate": [
      4,
      1,
      7
    ],
    "probes": [
      {
        "offset": [
          0,
          -1,
          -1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          0,
          -2
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          -1,
          -1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -1,
          -2
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          1,
          -1,
          -1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          0,
          -2
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          -3
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          1,
          -2
        ],
        "expected_block": "aionbound:basalt_brick"
      }
    ]
  },
  {
    "structure": "burned_camp",
    "stamp": "aionbound.structure.ashen.burned_camp.discovered.v1",
    "anchor_id": "burned_camp_cache",
    "anchor_type": "minecraft:barrel",
    "anchor_coordinate": [
      10,
      1,
      6
    ],
    "probes": [
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -1,
          -1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -1,
          1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -2,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          -1,
          -1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          -1,
          1
        ],
        "expected_block": "aionbound:ash_soil"
      }
    ]
  },
  {
    "structure": "burned_camp",
    "stamp": "aionbound.structure.ashen.burned_camp.discovered.v1",
    "anchor_id": "burned_camp_rumor",
    "anchor_type": "minecraft:lectern",
    "anchor_coordinate": [
      2,
      1,
      6
    ],
    "probes": [
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -1,
          -1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -1,
          1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          -1,
          -1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          -1,
          1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -1,
          -2
        ],
        "expected_block": "aionbound:ash_soil"
      }
    ]
  },
  {
    "structure": "char_wagon",
    "stamp": "aionbound.structure.ashen.char_wagon.discovered.v1",
    "anchor_id": "char_wagon_trade",
    "anchor_type": "minecraft:barrel",
    "anchor_coordinate": [
      11,
      3,
      4
    ],
    "probes": [
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_log"
      },
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_log"
      },
      {
        "offset": [
          1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_log"
      },
      {
        "offset": [
          -2,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -1,
          0,
          -1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -1,
          0,
          1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -2,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_log"
      }
    ]
  },
  {
    "structure": "broken_bridge",
    "stamp": "aionbound.structure.ashen.broken_bridge.discovered.v1",
    "anchor_id": "broken_bridge_route",
    "anchor_type": "minecraft:lodestone",
    "anchor_coordinate": [
      3,
      3,
      4
    ],
    "probes": [
      {
        "offset": [
          0,
          1,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -1,
          1,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          0,
          1,
          -1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          0,
          1,
          1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          1,
          1,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -2,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -2,
          0,
          1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          0,
          -2
        ],
        "expected_block": "aionbound:basalt_pillar"
      }
    ]
  },
  {
    "structure": "broken_bridge",
    "stamp": "aionbound.structure.ashen.broken_bridge.discovered.v1",
    "anchor_id": "broken_bridge_cache",
    "anchor_type": "minecraft:barrel",
    "anchor_coordinate": [
      15,
      4,
      4
    ],
    "probes": [
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -2,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -1,
          0,
          -1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -1,
          0,
          1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          1,
          0,
          -1
        ],
        "expected_block": "aionbound:char_planks"
      }
    ]
  },
  {
    "structure": "basalt_arch",
    "stamp": "aionbound.structure.ashen.basalt_arch.discovered.v1",
    "anchor_id": "basalt_arch_cache",
    "anchor_type": "minecraft:barrel",
    "anchor_coordinate": [
      6,
      1,
      5
    ],
    "probes": [
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:cinder_gravel"
      },
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:cinder_gravel"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:cinder_gravel"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:cinder_gravel"
      },
      {
        "offset": [
          -2,
          0,
          0
        ],
        "expected_block": "aionbound:cinder_gravel"
      },
      {
        "offset": [
          -1,
          -1,
          0
        ],
        "expected_block": "aionbound:cinder_gravel"
      },
      {
        "offset": [
          -1,
          0,
          -1
        ],
        "expected_block": "aionbound:cinder_gravel"
      },
      {
        "offset": [
          0,
          -1,
          -1
        ],
        "expected_block": "aionbound:cinder_gravel"
      }
    ]
  },
  {
    "structure": "ash_watchtower",
    "stamp": "aionbound.structure.ashen.ash_watchtower.discovered.v1",
    "anchor_id": "ash_watchtower_stamp",
    "anchor_type": "minecraft:lodestone",
    "anchor_coordinate": [
      5,
      1,
      5
    ],
    "probes": [
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -2,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          -1,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      }
    ]
  },
  {
    "structure": "ash_watchtower",
    "stamp": "aionbound.structure.ashen.ash_watchtower.discovered.v1",
    "anchor_id": "ash_watchtower_notes",
    "anchor_type": "minecraft:lectern",
    "anchor_coordinate": [
      4,
      10,
      6
    ],
    "probes": [
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -2,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -1,
          0,
          -1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -1,
          0,
          1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          0,
          0,
          -2
        ],
        "expected_block": "aionbound:char_planks"
      }
    ]
  },
  {
    "structure": "ash_watchtower",
    "stamp": "aionbound.structure.ashen.ash_watchtower.discovered.v1",
    "anchor_id": "ash_watchtower_cache",
    "anchor_type": "minecraft:barrel",
    "anchor_coordinate": [
      7,
      10,
      6
    ],
    "probes": [
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -2,
          0,
          0
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -1,
          0,
          -1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          -1,
          0,
          1
        ],
        "expected_block": "aionbound:char_planks"
      },
      {
        "offset": [
          0,
          0,
          -2
        ],
        "expected_block": "aionbound:char_planks"
      }
    ]
  },
  {
    "structure": "ancient_kiln",
    "stamp": "aionbound.structure.ashen.ancient_kiln.discovered.v1",
    "anchor_id": "ancient_kiln_hearth",
    "anchor_type": "minecraft:lodestone",
    "anchor_coordinate": [
      7,
      3,
      7
    ],
    "probes": [
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          1,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          -2,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -2,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      }
    ]
  },
  {
    "structure": "ancient_kiln",
    "stamp": "aionbound.structure.ashen.ancient_kiln.discovered.v1",
    "anchor_id": "ancient_kiln_cache",
    "anchor_type": "minecraft:barrel",
    "anchor_coordinate": [
      3,
      2,
      10
    ],
    "probes": [
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          1,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -2,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      }
    ]
  },
  {
    "structure": "ancient_kiln",
    "stamp": "aionbound.structure.ashen.ancient_kiln.discovered.v1",
    "anchor_id": "ancient_kiln_record",
    "anchor_type": "minecraft:lectern",
    "anchor_coordinate": [
      11,
      2,
      10
    ],
    "probes": [
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          1,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -2,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      }
    ]
  },
  {
    "structure": "ember_forge",
    "stamp": "aionbound.structure.ashen.ember_forge.discovered.v1",
    "anchor_id": "ember_forge_arena",
    "anchor_type": "minecraft:lodestone",
    "anchor_coordinate": [
      11,
      3,
      11
    ],
    "probes": [
      {
        "offset": [
          0,
          -2,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          -2,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          -3,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          -2,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          -2,
          1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          1,
          -2,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -2,
          -2,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          -3,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      }
    ]
  },
  {
    "structure": "ember_forge",
    "stamp": "aionbound.structure.ashen.ember_forge.discovered.v1",
    "anchor_id": "ember_forge_cache",
    "anchor_type": "minecraft:barrel",
    "anchor_coordinate": [
      17,
      3,
      11
    ],
    "probes": [
      {
        "offset": [
          0,
          1,
          0
        ],
        "expected_block": "aionbound:ash_log"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_pillar"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:basalt_pillar"
      },
      {
        "offset": [
          0,
          2,
          0
        ],
        "expected_block": "aionbound:ash_log"
      },
      {
        "offset": [
          0,
          -2,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          -2
        ],
        "expected_block": "aionbound:basalt_pillar"
      },
      {
        "offset": [
          0,
          0,
          2
        ],
        "expected_block": "aionbound:basalt_pillar"
      },
      {
        "offset": [
          0,
          3,
          0
        ],
        "expected_block": "aionbound:ash_log"
      }
    ]
  },
  {
    "structure": "ember_forge",
    "stamp": "aionbound.structure.ashen.ember_forge.discovered.v1",
    "anchor_id": "ember_forge_record",
    "anchor_type": "minecraft:lectern",
    "anchor_coordinate": [
      5,
      3,
      11
    ],
    "probes": [
      {
        "offset": [
          0,
          1,
          0
        ],
        "expected_block": "aionbound:ash_log"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_pillar"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:basalt_pillar"
      },
      {
        "offset": [
          0,
          2,
          0
        ],
        "expected_block": "aionbound:ash_log"
      },
      {
        "offset": [
          0,
          -2,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          -2
        ],
        "expected_block": "aionbound:basalt_pillar"
      },
      {
        "offset": [
          0,
          0,
          2
        ],
        "expected_block": "aionbound:basalt_pillar"
      },
      {
        "offset": [
          0,
          3,
          0
        ],
        "expected_block": "aionbound:ash_log"
      }
    ]
  },
  {
    "structure": "lava_shrine",
    "stamp": "aionbound.structure.ashen.lava_shrine.discovered.v1",
    "anchor_id": "lava_shrine_altar",
    "anchor_type": "minecraft:lodestone",
    "anchor_coordinate": [
      5,
      4,
      6
    ],
    "probes": [
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          -1,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          0,
          1
        ],
        "expected_block": "aionbound:basalt_brick"
      }
    ]
  },
  {
    "structure": "lava_shrine",
    "stamp": "aionbound.structure.ashen.lava_shrine.discovered.v1",
    "anchor_id": "lava_shrine_liturgy",
    "anchor_type": "minecraft:lectern",
    "anchor_coordinate": [
      5,
      2,
      10
    ],
    "probes": [
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:cinder_gravel"
      },
      {
        "offset": [
          -2,
          0,
          0
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          -1,
          0,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          0,
          -2
        ],
        "expected_block": "aionbound:basalt_brick"
      },
      {
        "offset": [
          0,
          1,
          -1
        ],
        "expected_block": "aionbound:basalt_brick"
      }
    ]
  },
  {
    "structure": "ash_cave",
    "stamp": "aionbound.structure.ashen.ash_cave.discovered.v1",
    "anchor_id": "ash_cave_depth",
    "anchor_type": "minecraft:lodestone",
    "anchor_coordinate": [
      8,
      1,
      11
    ],
    "probes": [
      {
        "offset": [
          -1,
          0,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          0,
          -1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          0,
          1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          1,
          0,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -2,
          0,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          0,
          -1
        ],
        "expected_block": "aionbound:ash_soil"
      }
    ]
  },
  {
    "structure": "ash_cave",
    "stamp": "aionbound.structure.ashen.ash_cave.discovered.v1",
    "anchor_id": "ash_cave_cache",
    "anchor_type": "minecraft:barrel",
    "anchor_coordinate": [
      4,
      2,
      9
    ],
    "probes": [
      {
        "offset": [
          0,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -2,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -1,
          -1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          0,
          -1,
          1
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          1,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -2,
          -1,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      },
      {
        "offset": [
          -1,
          -2,
          0
        ],
        "expected_block": "aionbound:ash_soil"
      }
    ]
  }
]);
