from __future__ import annotations

import json
import re
import uuid
import zipfile
from pathlib import Path
from typing import Any

from .io import write_json


def _safe_id(value: str) -> str:
    value = re.sub(r"[^a-z0-9_]+", "_", value.lower()).strip("_")
    return value or "converted_mod"


def _target_min_version(ir: dict[str, Any]) -> list[int]:
    target = ir.get("target") or {}
    markers = target.get("version_markers", [])
    for marker in markers:
        match = re.search(r"(\d+)\.(\d+)\.(\d+)", marker)
        if match:
            return [int(match.group(1)), int(match.group(2)), int(match.group(3))]
    return [1, 21, 90]


def _copy_assets(ir: dict[str, Any], output: Path, source_paths: list[Path]) -> list[dict[str, str]]:
    mappings: list[dict[str, str]] = []
    resource_root = output / "resource_pack" / "_source_assets"
    for source in source_paths:
        if not source.is_file() or source.suffix.lower() not in {".jar", ".zip"}:
            continue
        with zipfile.ZipFile(source) as archive:
            for name in archive.namelist():
                parts = name.split("/")
                if len(parts) < 4 or parts[0] != "assets" or parts[2] not in {"textures", "sounds"}:
                    continue
                destination = resource_root / parts[1] / "/".join(parts[2:])
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_bytes(archive.read(name))
                mappings.append({"source": f"{source.name}:{name}", "destination": str(destination.relative_to(output))})
    return mappings


def compile_bedrock(ir: dict[str, Any], plan: dict[str, Any], output_dir: str | Path) -> Path:
    output = Path(output_dir).expanduser().resolve()
    output.mkdir(parents=True, exist_ok=True)
    namespace = _safe_id((ir.get("mods") or [{}])[0].get("id", "converted_mod"))
    bp_uuid, rp_uuid, bp_data_uuid, bp_script_uuid, rp_data_uuid = [str(uuid.uuid4()) for _ in range(5)]
    version = [0, 1, 0]
    min_engine = _target_min_version(ir)
    script_api = ((ir.get("target") or {}).get("script_api_version") or "2.0.0")
    if isinstance(script_api, list):
        script_api = ".".join(map(str, script_api))

    bp = output / "behavior_pack"
    rp = output / "resource_pack"
    bp.mkdir(parents=True, exist_ok=True)
    rp.mkdir(parents=True, exist_ok=True)
    write_json(bp / "manifest.json", {
        "format_version": 2,
        "header": {"name": f"{namespace} reconstructed behavior", "description": "Generated by minecraft-compiler-baseline", "uuid": bp_uuid, "version": version, "min_engine_version": min_engine},
        "modules": [
            {"type": "data", "uuid": bp_data_uuid, "version": version},
            {"type": "script", "language": "javascript", "entry": "scripts/main.js", "uuid": bp_script_uuid, "version": version},
        ],
        "dependencies": [{"uuid": rp_uuid, "version": version}, {"module_name": "@minecraft/server", "version": script_api}],
        "metadata": {"generated_with": {"minecraft-compiler-baseline": "0.1.0"}, "license": "Generated scaffold; inspect source licenses before distribution"},
    })
    write_json(rp / "manifest.json", {
        "format_version": 2,
        "header": {"name": f"{namespace} reconstructed resources", "description": "Generated by minecraft-compiler-baseline", "uuid": rp_uuid, "version": version, "min_engine_version": min_engine},
        "modules": [{"type": "resources", "uuid": rp_data_uuid, "version": version}],
        "metadata": {"generated_with": {"minecraft-compiler-baseline": "0.1.0"}, "license": "Generated scaffold; inspect source licenses before distribution"},
    })
    script = """// Generated scaffold. No gameplay behavior is guessed here.\n// Add reviewed Behavior IR handlers as they become available.\nimport { system } from \"@minecraft/server\";\n\n// Keep the runtime hook explicit so later generated systems have one owner.\nexport function startGeneratedSystems() {\n  // system.runInterval(() => {}, 1);\n}\n\nstartGeneratedSystems();\n"""
    (bp / "scripts").mkdir(parents=True, exist_ok=True)
    (bp / "scripts" / "main.js").write_text(script, encoding="utf-8")
    write_json(bp / "conversion_ir.json", ir)
    write_json(bp / "conversion_plan.json", plan)

    source_paths = [
        Path(mod["source"].get("path", ""))
        for mod in ir.get("mods", [])
        if isinstance(mod.get("source"), dict) and mod["source"].get("path")
    ]
    mappings = _copy_assets(ir, output, source_paths)
    write_json(rp / "_source_asset_map.json", mappings)
    report = _report(ir, plan, namespace, mappings)
    (output / "conversion_report.md").write_text(report, encoding="utf-8")
    archive = output / "generated.mcaddon"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as bundle:
        for path in sorted(p for p in output.rglob("*") if p.is_file() and p != archive):
            bundle.write(path, path.relative_to(output).as_posix())
    return archive


def _report(ir: dict[str, Any], plan: dict[str, Any], namespace: str, mappings: list[dict[str, str]]) -> str:
    lines = [f"# Conversion report: `{namespace}`", "", "Generated by `minecraft-compiler-baseline` 0.1.0.", "", "## Result", "", f"- Technical fidelity estimate: **{plan['scores']['technical_fidelity']:.0%}**", f"- Gameplay fidelity estimate: **{plan['scores']['gameplay_fidelity']:.0%}**", f"- Confidence: **{plan['scores']['confidence']}**", f"- Copied texture/sound assets: **{len(mappings)}**", "", "These are inventory-level estimates, not runtime benchmark results.", "", "## Strategy plan", "", "| Feature | Count | Strategy | Status |", "|---|---:|---|---|"]
    for feature in plan["features"]:
        lines.append(f"| `{feature['feature']}` | {feature['count']} | `{feature['strategy']}` | {feature['status']} |")
    lines.extend(["", "## Matched patterns", ""])
    if plan["patterns"]:
        lines.extend(f"- `{item['id']}` via `{', '.join(item['matched_signals'])}`: {item['description']}" for item in plan["patterns"])
    else:
        lines.append("- None yet; add reviewed semantic evidence before generating behavior.")
    lines.extend(["", "## Warnings", "", *[f"- {warning}" for warning in plan["constraints"]], "", "## Source", "", f"- Input: `{ir.get('input', {}).get('path')}`", f"- Mods detected: **{len(ir.get('mods', []))}**", "- The live Bedrock server was not modified.", ""])
    return "\n".join(lines)
